---
title: "Step 01 of GeoToxMIE script"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Step 01 of GeoToxMIE script}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(GeoToxPackage)
options(tidyverse.quiet = TRUE)
library(tidyverse)
```

### Param settings

```{r params}
MC_iter <- 10 # Max 1000
```

### Load data

These data are not included in the package. Update paths to point where they are located on your computer.

```{r load_data}
# Load "county_cyp1a1_up"
load("~/dev/GeoTox/data/county_cyp1a1_up_20220201.RData")
# Load "css.sensitivity.age" and trim to MC_iter size
load("~/dev/GeoTox/data/css_by_county_sensitivity_age_20220228.RData")
css.sensitivity.age <- lapply(css.sensitivity.age, function(mat) mat[1:MC_iter, ])
# Load age data
age.data <- read.csv("~/dev/GeoTox/data/cc-est2019-alldata.csv")
```

### Format data

```{r format_data}
cyp1a1 <- split(county_cyp1a1_up, ~FIPS)

age <- age.data %>%
  filter(YEAR == 7) %>% # 7/1/2014 Census population
  mutate(FIPS = as.numeric(sprintf("%d%03d", STATE, COUNTY))) %>%
  select(FIPS, AGEGRP, TOT_POP) %>%
  # Update FIPS: https://www.ddorn.net/data/FIPS_County_Code_Changes.pdf
  mutate(FIPS = if_else(FIPS == 46102, 46113, FIPS)) %>% 
  filter(FIPS %in% unique(.env$county_cyp1a1_up$FIPS))
```

### Simulate age

```{r sim_age}
simulated_age <- lapply(split(age, ~FIPS), simulate_age, n = MC_iter)
```

### Simulate inhalation rate

```{r sim_IR}
simulated_IR <- lapply(simulated_age, simulate_inhalation_rate)
```

### Simulate external exposure

```{r sim_exposure}
simulated_exposure <- lapply(cyp1a1, simulate_exposure, n = MC_iter)
```

### Compute inhalation dose

```{r compute_ID}
inhalation_dose <- mapply(
  function(exposure, IR) {
    exposure / 1000 * IR
  },
  simulated_exposure,
  simulated_IR,
  SIMPLIFY = FALSE
)
```

### Compute in vitro dose

```{r compute_invitro}
invitro_dose <- mapply(
  function(ID, Css) {
    ID * Css
  },
  inhalation_dose,
  css.sensitivity.age,
  SIMPLIFY = FALSE
)
```

### Compute dose response

```{r compute_dose_response}
dose_response <- mapply(
  calc_dose_response,
  resp = cyp1a1,
  dose = invitro_dose,
  SIMPLIFY = FALSE
)
```
