---
title: "dev-conc-resp"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{dev-conc-resp}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(GeoToxPackage)
options(tidyverse.quiet = TRUE)
library(tidyverse)
```

### Load data

```{r load_data}
# Load dose response data
load("~/dev/GeoTox/data/LTEA_HepaRG_CYP1A1_up 41 chems for Kyle 220131.RData")
ice_data <- cdat; rm(cdat)

# Load "county_cyp1a1_up"
# Contains TCPL 3-parameter Hill fits for comparison
# TODO sensitivity vignette uses county_cyp1a1_up_20220201.RData, different?
load("~/dev/GeoTox/data/archived_outputs/county_cyp1a1_up_20211109.RData")
```

### Format data

```{r format_data}
# Split dose response data by chemical
ice_conc_resp <- split(as.data.frame(ice_data), ~casn)

# Extract TCPL fits for specified chemicals
tcpl <- county_cyp1a1_up %>%
  distinct(casrn, .keep_all = TRUE) %>%
  filter(casrn %in% names(ice_conc_resp))
```

### 2-parameter Hill fit

```{r fits}
fits <- lapply(ice_conc_resp, function(df) {
  fit <- fit_hill(df$logc, df$resp)
  fit$chnm <- df$chnm[1]
  fit$casn <- df$casn[1]
  fit
})
```

### Extract fit parameters

```{r fit_params}
fit_params <- do.call(
  rbind,
  lapply(fits, function(fit) {
    as_tibble(t(unlist(fit))) %>%
      rename(
        tp         = par.tp,
        tp.sd      = sds.tp,
        logAC50    = par.logAC50,
        logAC50.sd = sds.logAC50
      ) %>%
      select(
        tp, tp.sd, logAC50, logAC50.sd,
        logc_min, logc_max, resp_min, resp_max,
        AIC, chnm, casn
      ) %>% 
      mutate(across(tp:AIC, ~ as.numeric(.x)))
  })
)
```

### Replace NA sd with mean

```{r replace_na}
# TODO is this a good idea? See plots below
fit_params <- fit_params %>%
  mutate(
    tp.na      = is.na(tp.sd),      # for plot below
    logAC50.na = is.na(logAC50.sd), # for plot below
    tp.sd      = if_else(is.na(tp.sd), tp, tp.sd),
    logAC50.sd = if_else(is.na(logAC50.sd), logAC50, logAC50.sd)
  )
```

```{r}
xylim <- range(with(fit_params, c(tp, tp.sd)), na.rm = T)
ggplot(fit_params, aes(tp, tp.sd)) +
  geom_abline(linetype = 3) +
  geom_point(aes(color = tp.na), show.legend = FALSE) +
  coord_cartesian(xlim = xylim, ylim = xylim)
```

```{r}
xylim <- range(with(fit_params, c(logAC50, logAC50.sd)), na.rm = T)
ggplot(fit_params, aes(logAC50, logAC50.sd)) +
  geom_abline(linetype = 3) +
  geom_point(aes(color = logAC50.na), show.legend = FALSE) +
  coord_cartesian(xlim = xylim, ylim = xylim)
```

### Plot fits

```{r plot_fits}
log10_x <- seq(-3, 3, length.out = 1000)

y <- as.matrix(
  apply(fit_params[, c("tp", "logAC50")], 1, function(x) {
    x["tp"] / (1 + 10^(x["logAC50"] - log10_x))
  })
)
colnames(y) <- fit_params$casn
y <- as_tibble(y) %>% mutate(x = 10^log10_x, .before = 1)

ggplot(y %>% pivot_longer(!x), aes(x, value, color = name)) +
  geom_line(show.legend = FALSE) +
  scale_x_log10(labels = scales::label_math(10^.x, format = log10))
```
