---
title: "GeoTox Introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GeoTox Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette covers basic use of package functions. Package data, `geo_tox_data`, is used throughout the examples and details on how it was created can be found in the "GeoTox Package Data" vignette.

```{r setup, message=FALSE}
library(GeoTox)
library(dplyr)

set.seed(2357)

n <- 5 # Sample size
m <- 100 # Number of regions
idx <- if (m < 100) sample(1:100, m) else 1:100

# Load new geo_tox_data, not in package yet
load("~/dev/GeoTox/data-new/geo_tox_data.RData")
```

# Analysis of single assay

```{r}
dose_response <- geo_tox_data$dose_response |> 
  filter(endp == "TOX21_H2AX_HTRF_CHO_Agonist_ratio",
         call == "Active")
hill_params <- fit_hill(split(dose_response, ~casn)) |> 
  filter(!tp.sd.imputed, !logAC50.sd.imputed)
casn <- sort(hill_params$name)
exposure <- geo_tox_data$exposure |> filter(CASRN %in% .env$casn)
simulated_css <- geo_tox_data$simulated_css[casn]
```

Create object, run simulations and computations

```{r, warning=FALSE}
geoTox <- GeoTox() |> 
  # Set region and group boundaries (for plotting)
  set_boundaries(region = geo_tox_data$boundaries$county,
                 group  = geo_tox_data$boundaries$state) |> 
  # Estimated Hill parameters
  set_hill_params(hill_params) |>
  # Simulate populations for each region
  simulate_population(age           = split(geo_tox_data$age, ~FIPS)[idx],
                      obesity       = geo_tox_data$obesity[idx, ],
                      exposure      = split(exposure, ~FIPS)[idx],
                      expos_label   = "CASRN",
                      simulated_css = simulated_css,
                      n             = n) |> 
  # Calculate response
  calculate_response() |> 
  # Perform sensitivity analysis
  sensitivity_analysis()

geoTox
```

Plot outputs

```{r, fig.width = 7, fig.height = 3, fig.align = 'center'}
plot(geoTox)
plot(geoTox, type = "hill")
plot(geoTox, type = "exposure")
plot(geoTox, type = "sensitivity")
```
