---
title: "GeoTox Manuscript Analysis 1"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GeoTox Manuscript Analysis 1}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette covers basic use of package functions. Package data, `geo_tox_data`, is used throughout the examples and details on how it was created can be found in the "GeoTox Package Data" vignette.

```{r setup}

pak::pkg_install("NIEHS/GeoTox@sm-kpm-dev")
library(GeoTox)
suppressPackageStartupMessages({
  library(tidyverse)
  library(sf)
})

base_path <- "/ddn/gs1/home/messierkp/group_prj_local/GeoTox"

set.seed(2357)

n <- 500 # Sample size
m <- 100 # Number of regions
idx <- if (m < 100) sample(1:100, m) else 1:100
# Load new geo_tox_data, not in package yet
load(paste0(base_path,"/data/geo_tox_data_manuscript.RData"))
```

# Analysis of single assay

```{r, Calculating necessary inputs}
dose_response <- geo_tox_data$dose_response |> 
  filter(endp == "TOX21_H2AX_HTRF_CHO_Agonist_ratio",
         call == "Active")
hill_params <- fit_hill(split(dose_response, ~casn))
hill_filter <- hill_params$logAC50.sd < 0.95 * hill_params$logAC50
casn <- sort(unique(dose_response$casn))[hill_filter]
exposure <- geo_tox_data$exposure |> filter(CASRN %in% .env$casn)
simulated_css <- geo_tox_data$simulated_css[casn]
```

Create object, run simulations and computations

```{r, Running the full GeoTox analysis}
suppressWarnings(
  geoTox <- GeoTox() |> 
    # Set region and group boundaries (for plotting)
    set_boundaries(region = geo_tox_data$boundaries$county,
                   group  = geo_tox_data$boundaries$state) |> 
    # Simulate populations for each region
    simulate_population(age           = split(geo_tox_data$age, ~FIPS)[idx],
                        obesity       = geo_tox_data$obesity[idx, ],
                        exposure      = split(exposure, ~FIPS)[idx],
                        expos_label   = "CASRN",
                        simulated_css = simulated_css,
                        n             = n) |> 
    # Calculate response using estimated Hill parameters
    calculate_response(hill_params) |> 
    # Perform sensitivity analysis
    sensitivity_analysis()
)

geoTox
```

Plot outputs

```{r, fig.width = 7, fig.height = 3, fig.align = 'center', plotting}
plot(geoTox, quantiles = 0.5, quantile_labels = "median")
plot(geoTox, type = "hill")
plot(geoTox, type = "exposure")
plot(geoTox, type = "sensitivity")
```
